//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     161
#define IDB_INIBG                       162
#define IDB_LOADAD                      163
#define IDB_BITMAP4                     165
#define IDB_CHOOSE                      165
#define IDB_JOIN1                       166
#define IDB_BITMAP6                     167
#define IDB_JOIN2                       167
#define IDB_DAVID                       170
#define IDB_TEMPLATE                    171
#define IDB_DEEP                        172
#define IDB_WHITEPLAYER                 173
#define IDB_BLUEPLAYER                  174
#define IDB_PNG1                        175
#define IDB_INIJOINWHITE                176
#define IDB_BITMAP5                     179
#define IDB_INIJOINBLUE                 179
#define IDB_TEMPLATEBLUE                180
#define IDB_TEMPLATEWHITE               181
#define IDB_DAVIDNAMEWHITE              182
#define IDB_DAVIDNAMEBLUE               183
#define IDB_DEEPNAMEWHITE               184
#define IDB_DEEPNAMEBLUE                185
#define IDB_TEAM                        186
#define IDB_COUNTDOWN1                  187
#define IDB_COUNTDOWN2                  188
#define IDB_COUNTDOWN3                  189
#define IDB_COUNTDOWN4                  190
#define IDB_COUNTDOWN5                  191
#define IDB_GAMEMENU                    192
#define IDB_BITMAP7                     193
#define IDB_STAGEONEBG                  193
#define IDB_MENU2                       194
#define IDB_MENU3                       195
#define IDB_MENU4                       196
#define IDB_MENU5                       197
#define IDB_PNG2                        198
#define IDB_MENU6                       199
#define IDB_SMALLTEMPLATE               200
#define IDB_BLOOD                       201
#define IDB_MAGIC                       202
#define IDB_SMALLDAVID                  203
#define IDB_BITMAP9                     204
#define IDB_SMALLDEEP                   204
#define IDB_STAGEONEWHOLE               205
#define IDB_BITMAP10                    206
#define IDB_UPBLOCK                     206
#define IDB_PNG3                        208
#define IDB_STAGETWOBACKGROUND          213
#define IDB_BITMAP8                     227
#define IDB_STAGETHREEBACKGROUND        227
#define IDB_LOSE                        228
#define IDB_BITMAP12                    229
#define IDB_WIN                         229
#define IDB_START_MENU1                 230
#define IDB_START_MENU2                 231
#define IDB_START_MENU3                 232
#define IDB_START_MENU4                 233
#define IDB_START_MENU5                 234
#define IDB_START_MENU6                 235
#define IDB_START_MENU7                 236
#define IDB_BITMAP19                    237
#define IDB_START_MENU8                 237
#define IDB_BITMAP11                    238
#define IDB_ABOUT                       238
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
